//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFactoryNET.Module.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IOdlService")]
    public interface IOdlService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOdlService/AvviaOdl", ReplyAction="http://tempuri.org/IOdlService/AvviaOdlResponse")]
        void AvviaOdl(int oid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOdlServiceChannel : XFactoryNET.Module.Services.IOdlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdlServiceClient : System.ServiceModel.ClientBase<XFactoryNET.Module.Services.IOdlService>, XFactoryNET.Module.Services.IOdlService {
        
        public OdlServiceClient() {
        }
        
        public OdlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AvviaOdl(int oid) {
            base.Channel.AvviaOdl(oid);
        }
    }
}
