//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFactoryNET.Custom.Panzoo.Module.Services.Dosaggio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Dosaggio.ISvcDosaggio")]
    public interface ISvcDosaggio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/Arresta", ReplyAction="http://tempuri.org/ISvcDosaggio/ArrestaResponse")]
        void Arresta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/Avvia", ReplyAction="http://tempuri.org/ISvcDosaggio/AvviaResponse")]
        void Avvia(int oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/CurrMisc", ReplyAction="http://tempuri.org/ISvcDosaggio/CurrMiscResponse")]
        int CurrMisc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/GetPeso", ReplyAction="http://tempuri.org/ISvcDosaggio/GetPesoResponse")]
        float GetPeso(int iBil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/IdOdL", ReplyAction="http://tempuri.org/ISvcDosaggio/IdOdLResponse")]
        int IdOdL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/NrIngrediente", ReplyAction="http://tempuri.org/ISvcDosaggio/NrIngredienteResponse")]
        int NrIngrediente(int iBil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/NrMisc", ReplyAction="http://tempuri.org/ISvcDosaggio/NrMiscResponse")]
        int NrMisc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/QtàEstratta", ReplyAction="http://tempuri.org/ISvcDosaggio/QtàEstrattaResponse")]
        float QtàEstratta(int iBil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/Running", ReplyAction="http://tempuri.org/ISvcDosaggio/RunningResponse")]
        bool Running();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/StatoBilancia", ReplyAction="http://tempuri.org/ISvcDosaggio/StatoBilanciaResponse")]
        bool StatoBilancia(int iBil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcDosaggio/StopMisc", ReplyAction="http://tempuri.org/ISvcDosaggio/StopMiscResponse")]
        void StopMisc(int nrMisc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcDosaggioChannel : XFactoryNET.Custom.Panzoo.Module.Services.Dosaggio.ISvcDosaggio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcDosaggioClient : System.ServiceModel.ClientBase<XFactoryNET.Custom.Panzoo.Module.Services.Dosaggio.ISvcDosaggio>, XFactoryNET.Custom.Panzoo.Module.Services.Dosaggio.ISvcDosaggio {
        
        public SvcDosaggioClient() {
        }
        
        public SvcDosaggioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcDosaggioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcDosaggioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcDosaggioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Arresta() {
            base.Channel.Arresta();
        }
        
        public void Avvia(int oid) {
            base.Channel.Avvia(oid);
        }
        
        public int CurrMisc() {
            return base.Channel.CurrMisc();
        }
        
        public float GetPeso(int iBil) {
            return base.Channel.GetPeso(iBil);
        }
        
        public int IdOdL() {
            return base.Channel.IdOdL();
        }
        
        public int NrIngrediente(int iBil) {
            return base.Channel.NrIngrediente(iBil);
        }
        
        public int NrMisc() {
            return base.Channel.NrMisc();
        }
        
        public float QtàEstratta(int iBil) {
            return base.Channel.QtàEstratta(iBil);
        }
        
        public bool Running() {
            return base.Channel.Running();
        }
        
        public bool StatoBilancia(int iBil) {
            return base.Channel.StatoBilancia(iBil);
        }
        
        public void StopMisc(int nrMisc) {
            base.Channel.StopMisc(nrMisc);
        }
    }
}
