//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFactoryNET.Custom.MM1.Module.Services.Odl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Odl.ISvcOdl")]
    public interface ISvcOdl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcOdl/AvviaOdl", ReplyAction="http://tempuri.org/ISvcOdl/AvviaOdlResponse")]
        void AvviaOdl(int oid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcOdlChannel : XFactoryNET.Custom.MM1.Module.Services.Odl.ISvcOdl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcOdlClient : System.ServiceModel.ClientBase<XFactoryNET.Custom.MM1.Module.Services.Odl.ISvcOdl>, XFactoryNET.Custom.MM1.Module.Services.Odl.ISvcOdl {
        
        public SvcOdlClient() {
        }
        
        public SvcOdlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcOdlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcOdlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcOdlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AvviaOdl(int oid) {
            base.Channel.AvviaOdl(oid);
        }
    }
}
