//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFactoryNET.Custom.MM1.Module.Services.Pesa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Pesa.ISvcPesa")]
    public interface ISvcPesa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcPesa/LeggiPeso", ReplyAction="http://tempuri.org/ISvcPesa/LeggiPesoResponse")]
        float LeggiPeso(string codicePesa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcPesaChannel : XFactoryNET.Custom.MM1.Module.Services.Pesa.ISvcPesa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcPesaClient : System.ServiceModel.ClientBase<XFactoryNET.Custom.MM1.Module.Services.Pesa.ISvcPesa>, XFactoryNET.Custom.MM1.Module.Services.Pesa.ISvcPesa {
        
        public SvcPesaClient() {
        }
        
        public SvcPesaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcPesaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcPesaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcPesaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float LeggiPeso(string codicePesa) {
            return base.Channel.LeggiPeso(codicePesa);
        }
    }
}
